#include "shader_archive.h"

#include <cstring>
#include <mutex>

#include <fmt/format.h>
#include <zlib.h>

namespace rex::graphics::gta4_webgpu {
namespace {
// Generated by tools/webgpu/spirv_to_wgsl.py from the stock shader cache.
constexpr uint8_t kArchive[] = {
#embed GTA4_WEBGPU_SHADER_ARCHIVE
};
constexpr char kMagic[8] = {'L', 'R', 'W', 'G', 'S', 'L', '0', '5'};

class Reader {
 public:
  explicit Reader(std::span<const uint8_t> bytes) : bytes_(bytes) {}
  bool U32(uint32_t& value) { return Copy(&value, sizeof(value)); }
  bool U64(uint64_t& value) { return Copy(&value, sizeof(value)); }
  bool Bytes(size_t size, std::span<const uint8_t>& out) {
    if (size > bytes_.size() - offset_) return false;
    out = bytes_.subspan(offset_, size);
    offset_ += size;
    return true;
  }
  bool Align4() {
    const size_t aligned = (offset_ + 3) & ~size_t(3);
    if (aligned > bytes_.size()) return false;
    offset_ = aligned;
    return true;
  }
  bool done() const { return offset_ == bytes_.size(); }

 private:
  bool Copy(void* out, size_t size) {
    if (size > bytes_.size() - offset_) return false;
    std::memcpy(out, bytes_.data() + offset_, size);  // Little-endian host.
    offset_ += size;
    return true;
  }
  std::span<const uint8_t> bytes_;
  size_t offset_ = 0;
};
}  // namespace

bool ShaderArchive::Load(std::string& error) {
  z_stream stream{};
  if (inflateInit(&stream) != Z_OK) {
    error = "zlib initialization failed";
    return false;
  }
  stream.next_in = const_cast<Bytef*>(kArchive);
  stream.avail_in = uInt(sizeof(kArchive));
  std::vector<uint8_t> output(sizeof(kArchive) * 8);
  int status = Z_OK;
  while (status == Z_OK) {
    if (stream.total_out == output.size()) output.resize(output.size() * 2);
    stream.next_out = output.data() + stream.total_out;
    stream.avail_out = uInt(output.size() - stream.total_out);
    status = inflate(&stream, Z_NO_FLUSH);
  }
  const size_t size = stream.total_out;
  inflateEnd(&stream);
  if (status != Z_STREAM_END) {
    error = fmt::format("shader archive is corrupt (zlib status {})", status);
    return false;
  }
  output.resize(size);
  storage_ = std::move(output);
  return Parse(storage_, error);
}

bool ShaderArchive::Parse(std::span<const uint8_t> bytes, std::string& error) {
  Reader reader(bytes);
  std::span<const uint8_t> magic;
  uint32_t count = 0;
  if (!reader.Bytes(sizeof(kMagic), magic) || std::memcmp(magic.data(), kMagic, sizeof(kMagic)) ||
      !reader.U32(count)) {
    error = "shader archive header is invalid";
    return false;
  }
  for (uint32_t i = 0; i < count; ++i) {
    uint64_t hash = 0;
    uint32_t stage = 0, variant = 0, texture_mask = 0, cube_mask = 0, sampler_mask = 0;
    uint32_t specialization = 0, outputs = 0, attribute_count = 0, length = 0;
    std::span<const uint8_t> attributes, code;
    if (!reader.U64(hash) || !reader.U32(stage) || !reader.U32(variant) ||
        !reader.U32(texture_mask) || !reader.U32(cube_mask) || !reader.U32(sampler_mask) ||
        !reader.U32(specialization) || !reader.U32(outputs) || !reader.U32(attribute_count) ||
        !reader.Bytes(attribute_count, attributes) || !reader.Align4() || !reader.U32(length) ||
        !reader.Bytes(length, code) || !reader.Align4() || stage > 1 || variant > 1) {
      error = fmt::format("shader archive record {} is invalid", i);
      return false;
    }
    auto& record = records_[stage][hash];
    record.hash = hash;
    record.stage = gta4_native::ShaderStage(stage);
    record.texture_mask = texture_mask;
    record.cube_mask = cube_mask;
    record.sampler_mask = sampler_mask;
    record.specialization_mask = specialization;
    record.color_output_mask = outputs;
    record.attributes.assign(attributes.begin(), attributes.end());
    const std::string_view text(reinterpret_cast<const char*>(code.data()), code.size());
    (variant ? record.late : record.early) = text;
  }
  if (!reader.done()) {
    error = "shader archive has trailing bytes";
    return false;
  }
  return true;
}

const ShaderRecord* ShaderArchive::Find(uint64_t hash, gta4_native::ShaderStage stage) const {
  const uint32_t index = uint32_t(stage);
  if (index > 1) return nullptr;
  const auto found = records_[index].find(hash);
  return found == records_[index].end() || found->second.early.empty() ? nullptr
                                                                         : &found->second;
}

const ShaderArchive* GetShaderArchive(std::string& error) {
  static std::once_flag once;
  static ShaderArchive archive;
  static std::string load_error;
  static bool loaded = false;
  std::call_once(once, [] { loaded = archive.Load(load_error); });
  if (!loaded) {
    error = load_error;
    return nullptr;
  }
  return &archive;
}

}  // namespace rex::graphics::gta4_webgpu
